export type WorldCity = {
  city: string;
  country: string;
  region: "Africa" | "Asia" | "Europe" | "Middle East" | "North America" | "Oceania" | "South America";
};

// A deliberately local, dependency-free catalog keeps profile values consistent
// and avoids sending every search query to a third-party geocoding service.
export const WORLD_CITIES: readonly WorldCity[] = [
  { city: "Abidjan", country: "Côte d’Ivoire", region: "Africa" },
  { city: "Accra", country: "Ghana", region: "Africa" },
  { city: "Addis Ababa", country: "Ethiopia", region: "Africa" },
  { city: "Alexandria", country: "Egypt", region: "Africa" },
  { city: "Cairo", country: "Egypt", region: "Africa" },
  { city: "Cape Town", country: "South Africa", region: "Africa" },
  { city: "Casablanca", country: "Morocco", region: "Africa" },
  { city: "Dakar", country: "Senegal", region: "Africa" },
  { city: "Dar es Salaam", country: "Tanzania", region: "Africa" },
  { city: "Johannesburg", country: "South Africa", region: "Africa" },
  { city: "Kampala", country: "Uganda", region: "Africa" },
  { city: "Kigali", country: "Rwanda", region: "Africa" },
  { city: "Lagos", country: "Nigeria", region: "Africa" },
  { city: "Nairobi", country: "Kenya", region: "Africa" },
  { city: "Tunis", country: "Tunisia", region: "Africa" },
  { city: "Almaty", country: "Kazakhstan", region: "Asia" },
  { city: "Bandung", country: "Indonesia", region: "Asia" },
  { city: "Bangkok", country: "Thailand", region: "Asia" },
  { city: "Beijing", country: "China", region: "Asia" },
  { city: "Bengaluru", country: "India", region: "Asia" },
  { city: "Busan", country: "South Korea", region: "Asia" },
  { city: "Cebu City", country: "Philippines", region: "Asia" },
  { city: "Chennai", country: "India", region: "Asia" },
  { city: "Chiang Mai", country: "Thailand", region: "Asia" },
  { city: "Da Nang", country: "Vietnam", region: "Asia" },
  { city: "Delhi", country: "India", region: "Asia" },
  { city: "Denpasar", country: "Indonesia", region: "Asia" },
  { city: "Dhaka", country: "Bangladesh", region: "Asia" },
  { city: "Guangzhou", country: "China", region: "Asia" },
  { city: "Hanoi", country: "Vietnam", region: "Asia" },
  { city: "Ho Chi Minh City", country: "Vietnam", region: "Asia" },
  { city: "Hong Kong", country: "Hong Kong", region: "Asia" },
  { city: "Hyderabad", country: "India", region: "Asia" },
  { city: "Incheon", country: "South Korea", region: "Asia" },
  { city: "Jakarta", country: "Indonesia", region: "Asia" },
  { city: "Kathmandu", country: "Nepal", region: "Asia" },
  { city: "Kuala Lumpur", country: "Malaysia", region: "Asia" },
  { city: "Kyoto", country: "Japan", region: "Asia" },
  { city: "Lahore", country: "Pakistan", region: "Asia" },
  { city: "Macau", country: "Macau", region: "Asia" },
  { city: "Makassar", country: "Indonesia", region: "Asia" },
  { city: "Manila", country: "Philippines", region: "Asia" },
  { city: "Medan", country: "Indonesia", region: "Asia" },
  { city: "Mumbai", country: "India", region: "Asia" },
  { city: "Nagoya", country: "Japan", region: "Asia" },
  { city: "Osaka", country: "Japan", region: "Asia" },
  { city: "Phnom Penh", country: "Cambodia", region: "Asia" },
  { city: "Seoul", country: "South Korea", region: "Asia" },
  { city: "Shanghai", country: "China", region: "Asia" },
  { city: "Shenzhen", country: "China", region: "Asia" },
  { city: "Singapore", country: "Singapore", region: "Asia" },
  { city: "Surabaya", country: "Indonesia", region: "Asia" },
  { city: "Taipei", country: "Taiwan", region: "Asia" },
  { city: "Tokyo", country: "Japan", region: "Asia" },
  { city: "Ulaanbaatar", country: "Mongolia", region: "Asia" },
  { city: "Yogyakarta", country: "Indonesia", region: "Asia" },
  { city: "Amsterdam", country: "Netherlands", region: "Europe" },
  { city: "Athens", country: "Greece", region: "Europe" },
  { city: "Barcelona", country: "Spain", region: "Europe" },
  { city: "Belgrade", country: "Serbia", region: "Europe" },
  { city: "Berlin", country: "Germany", region: "Europe" },
  { city: "Brussels", country: "Belgium", region: "Europe" },
  { city: "Bucharest", country: "Romania", region: "Europe" },
  { city: "Budapest", country: "Hungary", region: "Europe" },
  { city: "Copenhagen", country: "Denmark", region: "Europe" },
  { city: "Dublin", country: "Ireland", region: "Europe" },
  { city: "Edinburgh", country: "United Kingdom", region: "Europe" },
  { city: "Helsinki", country: "Finland", region: "Europe" },
  { city: "Istanbul", country: "Türkiye", region: "Europe" },
  { city: "Lisbon", country: "Portugal", region: "Europe" },
  { city: "London", country: "United Kingdom", region: "Europe" },
  { city: "Madrid", country: "Spain", region: "Europe" },
  { city: "Manchester", country: "United Kingdom", region: "Europe" },
  { city: "Milan", country: "Italy", region: "Europe" },
  { city: "Munich", country: "Germany", region: "Europe" },
  { city: "Oslo", country: "Norway", region: "Europe" },
  { city: "Paris", country: "France", region: "Europe" },
  { city: "Prague", country: "Czechia", region: "Europe" },
  { city: "Rome", country: "Italy", region: "Europe" },
  { city: "Stockholm", country: "Sweden", region: "Europe" },
  { city: "Vienna", country: "Austria", region: "Europe" },
  { city: "Warsaw", country: "Poland", region: "Europe" },
  { city: "Zurich", country: "Switzerland", region: "Europe" },
  { city: "Abu Dhabi", country: "United Arab Emirates", region: "Middle East" },
  { city: "Amman", country: "Jordan", region: "Middle East" },
  { city: "Beirut", country: "Lebanon", region: "Middle East" },
  { city: "Doha", country: "Qatar", region: "Middle East" },
  { city: "Dubai", country: "United Arab Emirates", region: "Middle East" },
  { city: "Jeddah", country: "Saudi Arabia", region: "Middle East" },
  { city: "Kuwait City", country: "Kuwait", region: "Middle East" },
  { city: "Manama", country: "Bahrain", region: "Middle East" },
  { city: "Muscat", country: "Oman", region: "Middle East" },
  { city: "Riyadh", country: "Saudi Arabia", region: "Middle East" },
  { city: "Tel Aviv", country: "Israel", region: "Middle East" },
  { city: "Atlanta", country: "United States", region: "North America" },
  { city: "Austin", country: "United States", region: "North America" },
  { city: "Boston", country: "United States", region: "North America" },
  { city: "Chicago", country: "United States", region: "North America" },
  { city: "Dallas", country: "United States", region: "North America" },
  { city: "Denver", country: "United States", region: "North America" },
  { city: "Guadalajara", country: "Mexico", region: "North America" },
  { city: "Havana", country: "Cuba", region: "North America" },
  { city: "Honolulu", country: "United States", region: "North America" },
  { city: "Houston", country: "United States", region: "North America" },
  { city: "Los Angeles", country: "United States", region: "North America" },
  { city: "Mexico City", country: "Mexico", region: "North America" },
  { city: "Miami", country: "United States", region: "North America" },
  { city: "Montréal", country: "Canada", region: "North America" },
  { city: "New York", country: "United States", region: "North America" },
  { city: "Panama City", country: "Panama", region: "North America" },
  { city: "Portland", country: "United States", region: "North America" },
  { city: "San Diego", country: "United States", region: "North America" },
  { city: "San Francisco", country: "United States", region: "North America" },
  { city: "San José", country: "Costa Rica", region: "North America" },
  { city: "Seattle", country: "United States", region: "North America" },
  { city: "Toronto", country: "Canada", region: "North America" },
  { city: "Vancouver", country: "Canada", region: "North America" },
  { city: "Washington, D.C.", country: "United States", region: "North America" },
  { city: "Adelaide", country: "Australia", region: "Oceania" },
  { city: "Auckland", country: "New Zealand", region: "Oceania" },
  { city: "Brisbane", country: "Australia", region: "Oceania" },
  { city: "Melbourne", country: "Australia", region: "Oceania" },
  { city: "Perth", country: "Australia", region: "Oceania" },
  { city: "Sydney", country: "Australia", region: "Oceania" },
  { city: "Wellington", country: "New Zealand", region: "Oceania" },
  { city: "Asunción", country: "Paraguay", region: "South America" },
  { city: "Bogotá", country: "Colombia", region: "South America" },
  { city: "Buenos Aires", country: "Argentina", region: "South America" },
  { city: "Lima", country: "Peru", region: "South America" },
  { city: "Medellín", country: "Colombia", region: "South America" },
  { city: "Montevideo", country: "Uruguay", region: "South America" },
  { city: "Quito", country: "Ecuador", region: "South America" },
  { city: "Rio de Janeiro", country: "Brazil", region: "South America" },
  { city: "Santiago", country: "Chile", region: "South America" },
  { city: "São Paulo", country: "Brazil", region: "South America" },
] as const;

export const cityValue = (city: WorldCity) => `${city.city}, ${city.country}`;

