/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostDashboardRouteImport } from './routes/host-dashboard'
import { Route as HostRouteImport } from './routes/host'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as PPostIdRouteImport } from './routes/p.$postId'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push.dispatch'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDashboardRoute = HostDashboardRouteImport.update({
  id: '/host-dashboard',
  path: '/host-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PPostIdRoute = PPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push/dispatch',
  path: '/api/public/push/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/host': typeof HostRoute
  '/host-dashboard': typeof HostDashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tiers': typeof TiersRoute
  '/upgrade': typeof UpgradeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/reports': typeof AdminReportsRoute
  '/p/$postId': typeof PPostIdRoute
  '/u/$handle': typeof UHandleRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/host': typeof HostRoute
  '/host-dashboard': typeof HostDashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tiers': typeof TiersRoute
  '/upgrade': typeof UpgradeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/reports': typeof AdminReportsRoute
  '/p/$postId': typeof PPostIdRoute
  '/u/$handle': typeof UHandleRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/host': typeof HostRoute
  '/host-dashboard': typeof HostDashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tiers': typeof TiersRoute
  '/upgrade': typeof UpgradeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/reports': typeof AdminReportsRoute
  '/p/$postId': typeof PPostIdRoute
  '/u/$handle': typeof UHandleRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community-guidelines'
    | '/host'
    | '/host-dashboard'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/tiers'
    | '/upgrade'
    | '/verify-email'
    | '/admin/reports'
    | '/p/$postId'
    | '/u/$handle'
    | '/api/public/push/dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community-guidelines'
    | '/host'
    | '/host-dashboard'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/tiers'
    | '/upgrade'
    | '/verify-email'
    | '/admin/reports'
    | '/p/$postId'
    | '/u/$handle'
    | '/api/public/push/dispatch'
  id:
    | '__root__'
    | '/'
    | '/community-guidelines'
    | '/host'
    | '/host-dashboard'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/tiers'
    | '/upgrade'
    | '/verify-email'
    | '/admin/reports'
    | '/p/$postId'
    | '/u/$handle'
    | '/api/public/push/dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  HostRoute: typeof HostRoute
  HostDashboardRoute: typeof HostDashboardRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TiersRoute: typeof TiersRoute
  UpgradeRoute: typeof UpgradeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminReportsRoute: typeof AdminReportsRoute
  PPostIdRoute: typeof PPostIdRoute
  UHandleRoute: typeof UHandleRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-dashboard': {
      id: '/host-dashboard'
      path: '/host-dashboard'
      fullPath: '/host-dashboard'
      preLoaderRoute: typeof HostDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$postId': {
      id: '/p/$postId'
      path: '/p/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof PPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/dispatch': {
      id: '/api/public/push/dispatch'
      path: '/api/public/push/dispatch'
      fullPath: '/api/public/push/dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  HostRoute: HostRoute,
  HostDashboardRoute: HostDashboardRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TiersRoute: TiersRoute,
  UpgradeRoute: UpgradeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminReportsRoute: AdminReportsRoute,
  PPostIdRoute: PPostIdRoute,
  UHandleRoute: UHandleRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
